Meta:
        file: 'Make_GeoJ_and_Graphs.py'

Config:
        plotFontsize: 50
        graphFile: "loaded_graph.p"
        genfile: "Temp/gens.p"
        logfile: "Temp/log.txt"
        movieFilePrefix: "MovieFiles/vid_min_manhattan" 
        plotGraph: True
        plotGraphFile: "GraphImages/full_G.png"
        plotCondensed: True
        plotCondensedFile: "GraphImages/condensed_graph_manhattan.png"
        plotBarcode: True
        plotBarcodeFileBase: "Barcodes/min_bar_manhattan"
        plotCycles: True
        plotCycleFileBase: "Barcodes/min_cycles_manhattan"
        ripsType: "min" # can be max or min
        cycleMovieType: "pers" # can be pers or impact, only affects movie
        